"""empty message

Revision ID: 008dd41fa863
Revises: cf53af89d723
Create Date: 2020-04-30 09:36:50.416217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008dd41fa863'
down_revision = 'cf53af89d723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe__ingredient', sa.Column('group', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe__ingredient', 'group')
    # ### end Alembic commands ###
