"""empty message

Revision ID: 110d6369082d
Revises: 253d9979103c
Create Date: 2020-05-10 12:00:37.960192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110d6369082d'
down_revision = '253d9979103c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping', sa.Column('ingredient_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping', 'ingredient_id')
    # ### end Alembic commands ###
