"""empty message

Revision ID: 253d9979103c
Revises: 78e73ef028e6
Create Date: 2020-05-01 19:18:24.246800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253d9979103c'
down_revision = '78e73ef028e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'description')
    # ### end Alembic commands ###
