"""empty message

Revision ID: 78e73ef028e6
Revises: 008dd41fa863
Create Date: 2020-04-30 09:42:06.126349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e73ef028e6'
down_revision = '008dd41fa863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe__ingredient', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe__ingredient', 'order')
    # ### end Alembic commands ###
