"""empty message

Revision ID: 98ecf56be596
Revises: 4bc45b371fab
Create Date: 2020-04-11 19:42:13.398411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ecf56be596'
down_revision = '4bc45b371fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('has_image', sa.Boolean(), nullable=True))
    op.add_column('recipe', sa.Column('has_photo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'has_photo')
    op.drop_column('recipe', 'has_image')
    # ### end Alembic commands ###
